name="personal-ai"
main="src/index.ts"

compatibility_date = "2022-11-22"

kv_namespaces = [
    { binding = "personal_ai_chats", id = "3bbc252bd55445db803f457817178ce6", preview_id = "a176cbd87ca842c3ad5191efe60c88d9" }
]

[vars]
AI_MODEL="gpt-4-0125-preview"
MAX_CONVERSATION_MESSAGES="3"
API_URL="https://api.g4f.icu/v1"
OPENAI_API_KEY="sk-FRmDJ0Dq3JZUmCUi611dC99c4bF94aC4Be606d3a5dF0C58b"
OPENWEATHERMAP_API_KEY="4abd00cca1c4271563c13f8baca20376"
