name="personal-ai"
main="src/index.ts"

compatibility_date = "2022-11-22"

kv_namespaces = [
    { binding = "personal_ai_chats", id = "3bbc252bd55445db803f457817178ce6", preview_id = "a176cbd87ca842c3ad5191efe60c88d9" }
]

